# fai.conf -- FAI configuration (generated by fai-luks-builder)
#
# Docs: fai.conf(5)

# Location of the config space (local path for ISO builds)
FAI_CONFIG_SRC="file:///srv/fai/config"

# FAI flags for the installation
# verbose: show detailed output
# sshd:    start SSH daemon for remote debugging
# createvt: create virtual terminals (Alt-F2, Alt-F3)
FAI_FLAGS="verbose,sshd,createvt"

# Log protocol (none for ISO builds — logs saved locally)
FAI_LOGPROTO=
