# grub.cfg -- GRUB menu for FAI CD/USB (generated by fai-luks-builder)
#
# This is a minimal, unattended grub config that auto-starts installation
# without presenting a menu. Used by fai-cd -g.

set default=0
set timeout=3

menuentry "FAI -- Fully Automatic Installation (LUKS Server)" {
    linux  /boot/vmlinuz FAI_FLAGS=verbose,sshd,createvt FAI_ACTION=install FAI_CONFIG_SRC=file:///var/lib/fai/config ip=dhcp root=live:CDLABEL=FAI_CD rd.live.image
    initrd /boot/initrd.img
}

menuentry "FAI -- Boot from local disk" {
    set root=(hd0)
    chainloader +1
}
