# nfsroot.conf -- FAI nfsroot configuration (generated by fai-luks-builder)
#
# Docs: nfsroot.conf(5)

# Distribution and mirror for debootstrap
FAI_DEBOOTSTRAP="TEMPLATED_RELEASE http://deb.debian.org/debian"

# Packages to include in the nfsroot (the install environment, NOT the target).
# These are needed so setup-storage can create LUKS/LVM during installation.
NFSROOT_PACKAGES="cryptsetup lvm2 e2fsprogs dosfstools efibootmgr grub-efi-amd64-bin parted hdparm"

# Where to build the nfsroot
NFSROOT=/srv/fai/nfsroot

# FAI config directory
FAI_CONFIGDIR=/srv/fai/config
