# nfsroot.conf -- FAI nfsroot configuration (generated by fai-luks-builder)
#
# Docs: nfsroot.conf(5)

# Distribution and mirror for debootstrap
FAI_DEBOOTSTRAP="TEMPLATED_RELEASE http://deb.debian.org/debian"

# Packages to include in the nfsroot (the install environment, NOT the target).
# These are needed so setup-storage can create LUKS/LVM during installation.
NFSROOT_PACKAGES="cryptsetup lvm2 e2fsprogs dosfstools efibootmgr TEMPLATED_GRUB_EFI_PKG parted hdparm"

# Where to build the nfsroot
NFSROOT=/srv/fai/nfsroot

# TFTP root -- not used for ISO builds, but fai-setup requires it to be set
TFTPROOT=/srv/tftp/fai

# FAI config directory
FAI_CONFIGDIR=/srv/fai/config
